### ISSUE TITLE
[ADD]: Schema addition - Buyers

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/food-reservation-system#6]
## Task
Implement schema as mentioned in the reference for the table Buyers

**Refer to the [schema file](./schema-diagram/FRASchemaDiagram.drawio.png)**

## References:
- [PrismaIO Concepts](https://www.prisma.io/docs/concepts/components/prisma-client/crud)
- [PrismaIO reference on implementing CRUD](https://www.prisma.io/docs/concepts/components/prisma-client/crud)
- [PrismaIO reference on implementing Many to Many relations](https://prisma.io/docs/components/relations/many-to-many)

**Comment by RahulAhujatoo** [comment]
I would like to take this issue can I proceed?

**Comment by RahulAhujatoo** [comment]
There are no schemas to start with. Should I create new ones?

**Comment by AbhijithGanesh** [comment]
@RahulAhujatoo Thats a good call out! I'll create that as a linked issue and assign it to you! You can reference it on your PR

**Comment by AbhijithGanesh** [comment]
@RahulAhujatoo You can now send in another PR for the Model

**Comment by RahulAhujatoo** [comment]
Hey, I've added Buyers can you please review!
